name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build the Docker image and tag it for GHCR
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/arkiver:latest

      # Log in to GitHub Container Registry
      - name: Log into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Push the Docker image to GHCR
      - name: Push the Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/arkiver:latest

